name: Build release

on:
  push:
    branches: [ master ]
    paths:
      - LATEST_VERSION

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
      
    - name: Create release archive
      run: make
