name: Create release

on:
  push:
    branches: [ main ]
    paths:
      - LATEST_VERSION

  workflow_dispatch:

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2

    - name: Setup Swift
      uses: swift-actions/setup-swift@v1.15.0
      with:
        swift-version: "5.6"

    - name: Create workflow archive
      run: make

    - name: Read version number
      run: echo "VERSION=$(cat LATEST_VERSION)" >> $GITHUB_ENV

    - name: Create draft release
      uses: softprops/action-gh-release@v0.1.14
      with:
        body: |
          What's new:
          * TODO: populate change list.

          See Milestone [${{ env.VERSION }}](TODO: link to the correct milestone) for all fixes in this release.
        name: ${{ env.VERSION }}
        tag_name: ${{ env.VERSION }}
        files: "Linguee.Search-*.alfredworkflow"
        draft: true
        fail_on_unmatched_files: true
        generate_release_notes: true
