name: Run tests on commit

on:
  push:
    branches: [ main, develop ]

  workflow_dispatch:

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2

    - name: Setup Swift
      uses: swift-actions/setup-swift@v1.15.0
      with:
        swift-version: "5.6"

    - name: Run test
      run: make test

